### ISSUE TITLE
feat(Home): Immediately upcoming event

### ISSUE THREAD

**Issue by timhwang21** [newhavenio/newhavenio#42]
A small label of some sort by the first Meetup button in the hero section that says 'Next event in N days!' if there is an event this week.

**Comment by Quinncuatro** [comment]
> Perhaps we want to filter out smaller events like byte brunch?

Hold on this. We have a board meeting tomorrow where we're going to talk about our event cadence and series.

**Comment by timhwang21** [comment]
^ This is for "featured" events, stuff like the holiday party. I don't think it makes sense to call out the next Byte Brunch in a dedicated section on the homepage.

**Comment by timhwang21** [comment]
Thought about this a bit. Seems most appropriate to just have a small "next event in n days!" next to the meetup button.

**Comment by Quinncuatro** [comment]
Whatever you want to go with. If you go with the "here's the next event" thing, definitely include the Byte Brunches.

It's important for newer members to see the easier ways to get involved with the community.
