### ISSUE TITLE
feat(Partners): Partners page (sponsors / donations)

### ISSUE THREAD

**Issue by timhwang21** [newhavenio/newhavenio#49]
We have no partners 😅 Possibly a good long-term task.

- [ ] Write up a value proposition of partnering with us
- [ ] Design a CTA (contact form?)
- [ ] Make some sane layout
- [ ] Reach out to feasible orgs
  - SeeClickFix
  - Continuity
  - Acuity
  - Yale CS department
  - District / Code:FWD
  - M. Harris' group
- [ ] Possibly donation links -- these MUST be transparent (e.g. who the fuck currently controls the current bitcoin donation link?)
  - Transparency can possibly be a separate (sub?)page -- monthly/quarterly breakdowns or reports. Collab's reports can be inspiration (though they are for more in-depth than what we need or can do).

**Comment by Quinncuatro** [comment]
We're working on putting this list together amongst the board. Definitely a mk2 thing.
