### ISSUE TITLE
feat(Twitter): Consolidated Twitter feeds

### ISSUE THREAD

**Issue by timhwang21** [newhavenio/newhavenio#51]
Opt-in, live stream of consolidation of members' twitters.

**Comment by a-trost** [comment]
So this would be going off a list of twitter handles or a #newhavenio hashtag?

**Comment by timhwang21** [comment]
I was thinking the former (more controllable) but it's up in the air,
whatever people think is the best option. This is definitely not MVP IMO.

**Comment by a-trost** [comment]
Agreed.
