### ISSUE TITLE
feat: NHIO dev account for secrets

### ISSUE THREAD

**Issue by timhwang21** [newhavenio/newhavenio#86]
cc @a-trost and @quinncuatro

1. [ ] Create a dev@newhavenio.com
2. [ ] Register for all services using this account (@a-trost plz add anything that's missing!)
    - [ ] Join Slack & make this user an admin
    - [ ] Generate a Slack API key for this user
    - [ ] stdlib account
    - [ ] Netlify account
3. [ ] Share credentials for this account with whoever needs it via some password manager we all agree on (lastpass or 1pass?)

**Comment by Quinncuatro** [comment]
I've created the Netlify and GitHub account.

Everything will be infrastructure+service@newhaven.io

What do we need the stdlib account for?

**Comment by Quinncuatro** [comment]
stdlib account is infrastructure+stdlib@newhaven.io

What do we need the Slack one for?

**Comment by timhwang21** [comment]
To manage the API token for the slack cloud function that lets people
invite themselves

**Comment by Quinncuatro** [comment]
Word.

NHVIO-infra is an admin on Slack.

That should be everything. What plumbing do we need to do after @a-trost pushes the repo over?

**Comment by timhwang21** [comment]
The bullet points should cover everything -- we'll also need the new Slack token
